spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://jotanunes-db-get-info-database.b.aivencloud.com:21733/stock_manager?sslmode=require
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
        hibernate:
          format_sql: true
